CMTPATH=/home/shuang/c++/c++
CMT_tag=$(tag)
CMTROOT=/home/shuang/lhcb/contrib/CMT/v1r20p20090520
CMT_root=/home/shuang/lhcb/contrib/CMT/v1r20p20090520
CMTVERSION=v1r20p20090520
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/home/shuang/c++/c++/InstallArea/${CMTCONFIG}/bin:/home/shuang/lhcb/contrib/CMT/v1r20p20090520/${CMTBIN}:/home/shuang/lhcb/lhcb/LBSCRIPTS/LBSCRIPTS_v8r4p1/InstallArea/scripts:/home/shuang/lhcb/lcg/releases/LCG_74root6/Python/2.7.9/x86_64-slc6-gcc48-opt/bin:/home/shuang/lhcb/lhcb/COMPAT/COMPAT_v1r19/CompatSys/x86_64-slc6-gcc48-opt/bin:/home/shuang/lhcb/lcg/releases/LCG_74root6/gcc/4.8.1/x86_64-slc6/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/home/shuang/bin
CLASSPATH=/home/shuang/lhcb/contrib/CMT/v1r20p20090520/java
debug_option=-g
cc=gcc
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=c++
cppflags=-pipe -ansi -pedantic -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplink=$(cpp) $(cpplinkflags) $(cppdebugflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=${symlink}
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=lockfile 
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=/usr/bin/python ${CMTROOT}/mgr/cmt_svn_checkout.py 
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=cp 
uninstall_command=/bin/rm -f 
cmt_installarea_command=ln -fs 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-slc66-gcc481
chapter11_tag=$(tag)
CHAPTER11ROOT=/home/shuang/c++/c++/chapter11
chapter11_root=/home/shuang/c++/c++/chapter11
CHAPTER11VERSION=v0
chapter11_cmtpath=/home/shuang/c++/c++
chapter11_project=c++
tag=x86_64-slc6-gcc48-opt
package=chapter11
version=v0
PACKAGE_ROOT=$(CHAPTER11ROOT)
srcdir=../src
bin=../$(chapter11_tag)/
BIN=/home/shuang/c++/c++/chapter11/$(chapter11_tag)/
javabin=../classes/
mgrdir=cmt
project=c++
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(c++_installarea_prefix)/$(CMTCONFIG)/lib $(c++_installarea_prefix)/share/lib $(c++_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(chapter11_linkopts) 
c++_installarea_prefix=$(cmt_installarea_prefix)
c++_installarea_prefix_remove=$(c++_installarea_prefix)
LD_LIBRARY_PATH=/home/shuang/c++/c++/InstallArea/${CMTCONFIG}/lib:/home/shuang/lhcb/lcg/releases/LCG_74root6/gcc/4.8.1/x86_64-slc6/lib64:/home/shuang/lhcb/lcg/releases/LCG_74root6/Python/2.7.9/x86_64-slc6-gcc48-opt/lib
cmt_installarea_linkopts= -L/home/shuang/c++/c++/$(c++_installarea_prefix)/$(CMTCONFIG)/lib 
CMTINSTALLAREA=/home/shuang/c++/c++/$(cmt_installarea_prefix)
use_requirements=requirements $(CMT_root)/mgr/requirements 
use_includes= 
use_fincludes= $(use_includes)
use_stamps=  $(chapter11_stamps) 
use_cflags=  $(chapter11_cflags) 
use_pp_cflags=  $(chapter11_pp_cflags) 
use_cppflags=  $(chapter11_cppflags) 
use_pp_cppflags=  $(chapter11_pp_cppflags) 
use_fflags=  $(chapter11_fflags) 
use_pp_fflags=  $(chapter11_pp_fflags) 
includes= $(ppcmd)"$(srcdir)" $(use_includes)
fincludes= $(includes)
pra14_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
pra14_use_linkopts=  $(chapter11_linkopts) 
pra16_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
pra16_use_linkopts=  $(chapter11_linkopts) 
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
constituents= pra14 pra16 
all_constituents= $(constituents)
constituentsclean= pra16clean pra14clean 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make 
cmt_actions_constituentsclean= makeclean 
